[theme]
base = "light"
primaryColor = "#108455"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#191e1b"
font = "sans serif"
borderColor = "#e6e9e7"
dataframeBorderColor = "#f0f2f0"
dataframeHeaderBackgroundColor = "#f7f9f7"
